//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impossible transaction. Proof amount. ähnelt.
        /// </summary>
        internal static string amountImpossible {
            get {
                return ResourceManager.GetString("amountImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount must be a positive value. ähnelt.
        /// </summary>
        internal static string amountPositive {
            get {
                return ResourceManager.GetString("amountPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance must be a valid value ähnelt.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There must be at least one character before the @. ähnelt.
        /// </summary>
        internal static string mailCharakter {
            get {
                return ResourceManager.GetString("mailCharakter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There must not be a . at the start or end. ähnelt.
        /// </summary>
        internal static string mailDots {
            get {
                return ResourceManager.GetString("mailDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There must not be a . just before or after the @. ähnelt.
        /// </summary>
        internal static string mailDotsAt {
            get {
                return ResourceManager.GetString("mailDotsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail must contain exactly one @. ähnelt.
        /// </summary>
        internal static string mailExactAt {
            get {
                return ResourceManager.GetString("mailExactAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The part after the final . must be 2‐4 characters long and contain only letters. ähnelt.
        /// </summary>
        internal static string mailLength {
            get {
                return ResourceManager.GetString("mailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail must have at least one . after the @. ähnelt.
        /// </summary>
        internal static string mailOneDot {
            get {
                return ResourceManager.GetString("mailOneDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail contains invalid symbol(s). ähnelt.
        /// </summary>
        internal static string mailSymbols {
            get {
                return ResourceManager.GetString("mailSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This mail adress has already been used. ähnelt.
        /// </summary>
        internal static string mailUsed {
            get {
                return ResourceManager.GetString("mailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only letters of the alphabet allowed for name. ähnelt.
        /// </summary>
        internal static string nameLetters {
            get {
                return ResourceManager.GetString("nameLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name is null, empty or white space. ähnelt.
        /// </summary>
        internal static string nameNull {
            get {
                return ResourceManager.GetString("nameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer number has already been used. ähnelt.
        /// </summary>
        internal static string numberUsed {
            get {
                return ResourceManager.GetString("numberUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only letters of the alphabet allowed for surname. ähnelt.
        /// </summary>
        internal static string surnameLetters {
            get {
                return ResourceManager.GetString("surnameLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname is null, empty or white space. ähnelt.
        /// </summary>
        internal static string surnameNull {
            get {
                return ResourceManager.GetString("surnameNull", resourceCulture);
            }
        }
    }
}
